### ISSUE TITLE
Bugs from the recent version of Bleeding Winter

### ISSUE THREAD

**Issue by FoeFear** [CryAwakening/Bleeding-Winter#1]
When me and another staff member were setting up the bleeding winter server, we came across some bugs from the added mod, Realistic Block Physics. As I was looking around with this bug, I came across a couple of problems.

-If you try to place a block that floats (enchanting books), they are impossible to place. 
-Some blocks that have a base (the turrets from immersive engineering) are impossible to place as they break when placed. 
-When carpets and candles are placed on any wall/fence/bar, they have the ability to break any block below it (can go almost all the way to bedrock).
-Sticky pistons are useless as they can't stick to any block when there is air below to that block (this also includes slime blocks)

Minor bug
-Mobs are aggravated on creative mode

Update #1 with bugs
-soul sand cannot be placed as a tower
-any head placed on soul sand would break and would be converted to a skeleton skull

If you have any problems with this, let me know and I'll do what I can to show proof.

**Comment by CryAwakening** [comment]
Thanks for taking the time to report these issues:

Enchanting books being instantly destroyed has been fixed.
The turrets from immersive engineering (both) have been fixed.
Soul sand can now be towered to a limit (7 blocks) rather than disappearing on placement.
Currently the issue with wither skeleton skulls turning into regular will be tricky to fix as they share the same ID number.

Sticky pistons are designed to work alongside gravity since the actually pushed piston is not a block it will not hold a block unless another is supporting it. (I'll talk with the dev of the mod to see if he can find a fix)

Mobs are aggravated because of the version mobs 1.12.2 and sound attraction~

I'll see in the future if any of these can be resolved with the help of the original developer of the gravity mod.

**Comment by CryAwakening** [comment]
- Fixed an issue causing enchanting books to drop when placed.

- Fixed an issue causing gun turrets and chem turrets to drop when placed.

- Fixed an issue preventing soul sand from being placed vertically.

- Fixed an issue causing 

- Adjusted gravity to all post variations

- Candles are no longer affected by gravity and will drop if a block is not present below 

- Removed gravity from vanilla mob heads

- Removed gravity from The Twilight Forest trophies

- Removed gravity in the Nether

- Removed auto jump by default

- Updated gravity compatibility (several bug fixes)

- Updated Future Textures

**Comment by FoeFear** [comment]
Thanks for the update.
